templates:

  opensearch-requirements: &opensearch-requirements
    missingFileHandler: Error
    name: ""
    namespace: es-opensearch
    createNamespace: true
    chart: incubator/raw
    version: 0.2.3
    values:
      - ./elastic-opensearch/releases/{{ .Release.Name }}/values.yaml.gotmpl
    needs: []

  opensearch-nodegroup: &opensearch-nodegroup
    missingFileHandler: Error
    name: ""
    namespace: es-opensearch
    createNamespace: true
    chart: opensearch/opensearch
    version: 1.8.2
    values:
      - ./elastic-opensearch/releases/nodegroup/{{ .Release.Name }}/values.yaml.gotmpl
    needs: []

  opensearch-dashboards: &opensearch-dashboards
    missingFileHandler: Error
    name: ""
    namespace: es-opensearch
    createNamespace: true
    chart: opensearch/opensearch-dashboards
    version: 1.2.0
    values:
      - ./elastic-opensearch/releases/{{ .Release.Name }}/values.yaml.gotmpl
    needs: []
